# Generated by Django 2.2.4 on 2020-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_request_request_type_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_type',
            name='name',
        ),
        migrations.AddField(
            model_name='request_type',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ManyToManyField(to='accounts.Request_type'),
        ),
    ]
