# Generated by Django 2.2.4 on 2020-08-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200816_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Status'),
        ),
    ]
