# Generated by Django 2.2.4 on 2020-08-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200822_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Request_type',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
